=== ThiernoMahmouth/projet-XML-PHP/examen.dtd
<!ELEMENT examen(description, date, professeur, exercice+)>
    <!ELEMENT description EMPTY>
        <!ATTLIST description classe CDATA #REQUIRED
                            matiere CDATA #REQUIRED
                            semestre CDATA #REQUIRED
                            date CDATA #REQUIRED>
    <!ELEMENT professeur(prenom?, nom)>
        <!ELEMENT prenom(#PCDATA)>
        <!ELEMENT nom(#PCDATA)>    
    <!ELEMENT exercice (question+)>
        <!ATTLIST exercice numero CDATA #REQUIRED
                           nbPoint CDATA>
        <!ELEMENT nbPoint(#PCDATA)>
        <!ELEMENT question(libelle, option*)>
            <!ENTITY %typeRep ("repCourte" | "repLongue" | "repUnique" | "repMultiple") >
            <!ATTLIST question  numero CDATA #REQUIRED
                                nbPoint CDATA
                                type %typeRep; #REQUIRED>
            <!ELEMENT libelle (#PCDATA)>
            <!ELEMENT option (#PCDATA)>

=== ThiernoMahmouth/projet-XML-PHP/examComptaDESCAF22021-11-11.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE examen SYSTEM "examen.dtd">
<examen>
<description classe="DESCAF2" matiere="Compta" semestre="1" date="2021-11-11"/>
<professeur><prenom>DIALLO</prenom><nom>Gallo</nom></professeur>
<exercice numero="1" nbPoint="0">
    <question numero="1" nbPoint="12" type="repUnique">
        <libelle>Qui es tu?</libelle>
        <option>Humain</option>
        <option>Animal</option>
        <option>Djiin</option>
        <option>Ange</option>
    </question>
    <question numero="2" nbPoint="8" type="repLongue">
        <libelle>Couleurs du drapeau</libelle>
    </question>
    </exercice>
</examen>

=== ThiernoMahmouth/projet-XML-PHP/examGestionDESCAF22021-11-03.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE examen SYSTEM "examen.dtd">
<examen>
<description classe="DESCAF2" matiere="Gestion" semestre="2" date="2021-11-03"/><professeur><prenom>DIALLO</prenom><nom>Gallo</nom></professeur><exercice numero="1" nbPoint="0"><question numero="1" nbPoint="5" type="repUnique"><libelle>Est-ce vrai</libelle><option>vrai</option><option>faux</option></question><question numero="2" nbPoint="3" type="repMultiple"><libelle>plats preferes</libelle><option>mafe</option><option>riz</option><option>poulet</option></question></exercice><exercice numero="2" nbPoint="0"><question numero="1" nbPoint="2" type="repCourte"><libelle>Qui est de parler?</libelle></question></exercice></examen>

=== ThiernoMahmouth/projet-XML-PHP/examTelecomDIC3 TR2021-11-03.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE examen SYSTEM "examen.dtd">
<examen>
<description classe="DIC3 TR" matiere="Telecom" semestre="1" date="2021-11-03"/><professeur><prenom>DIALLO</prenom><nom>Gallo</nom></professeur><exercice numero="1" nbPoint="0"><question numero="1" nbPoint="2" type="repCourte"><libelle>Qui es tu?</libelle></question><question numero="2" nbPoint="3" type="repUnique"><libelle>Ta couleurs préférées ?</libelle><option>rouge</option><option>vert</option><option>noir</option></question></exercice><exercice numero="2" nbPoint="0"><question numero="1" nbPoint="5" type="repLongue"><libelle>Qui est en train de parler?</libelle></question></exercice></examen>
